AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudFormation Custom Resource for creating Amazon Cognito App Client.

Resources:
  CognitoAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cognito_app/
      Handler: app.handler
      Runtime: python3.7
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: 'arn:aws:logs:*:*:*'
            - Effect: Allow
              Action:
                - cognito-idp:*
              Resource: '*'

Outputs:
  CognitoAppFunction:
    Description: "ARN for Amazon Cognito app client custom resource function"
    Value: !GetAtt CognitoAppFunction.Arn
    Export:
      Name: "CognitoAppFunction"