AWSTemplateFormatVersion: "2010-09-09"
Description: Cognito User pool with User Pool Domain and Identity Service Provider
Transform: AWS::Serverless-2016-10-31

Parameters:
  Domain:
    Description: Amazon Cognito domain name.
    Type: String
    AllowedPattern: ^[0-9a-z]+(-[0-9a-z]+)*$
    ConstraintDescription: Prefixed domain names can only contain lower-case letters, numbers, and hyphens.

  ProviderDetails:
    Description: The identity provider details MetadataURL.
    Type: String

  CallbackURLs:
    Description: Callback URL(s) for sign in requests. Can contain multiple URLs by entering a comma after each URL.
    Type: CommaDelimitedList

  SignOutURLSs:
    Description: Sign out URL(s) for sign out requests. Can contain multiple URLs by entering a comma after each URL.
    Type: CommaDelimitedList

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AliasAttributes:
        - preferred_username
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Required: true
      UserPoolName: CfnCustomPool

  CognitoDomainConfig:
    Type: 'Custom::CognitoDomainConfig'
    Version: '1.0'
    Properties:
      ServiceToken: !ImportValue CognitoDomainFunction
      DomainName: !Ref Domain
      UserPoolId: !Ref CognitoUserPool

  CognitoIdpConfig:
    Type: 'Custom::CognitoIdpConfig'
    Version: '1.0'
    Properties:
      ServiceToken: !ImportValue CognitoIdpFunction
      UserPoolId: !Ref CognitoUserPool
      ProviderName: SignIn # Should be same as a provider name in CognitoAppConfig
      ProviderType: SAML
      ProviderDetails: !Ref ProviderDetails
      AttributeMapping: email

  CognitoAppConfig:
    Type: 'Custom::CognitoAppConfig'
    Version: '1.0'
    Properties:
      ServiceToken: !ImportValue CognitoAppFunction
      UserPoolId: !Ref CognitoUserPool
      ClientName: AppClient
      ProviderName: SignIn # Should be same as a provider name in CognitoIdpConfig
      CallbackURLs: !Ref CallbackURLs
      LogoutURLs: !Ref SignOutURLSs
    DependsOn:
      - CognitoIdpConfig
